server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # O Vite (React SPA) lida com as rotas
    location / {
        try_files $uri $uri/ /index.html;
    }
}
